import os
S = "\033[1;91m"
N = "\033[1;96m"
U = "\033[1;97m"
F = "\033[1;92m"
F666 = "\033[1;93m"
YourKing = "\033[1;95m"
YourKing = "\033[1;96m"
print(f"This Installation Takes 10-20 Min Please Wait Don't CloseThe App Before Installation ")
os.system('pip install requests')
os.system('pip install user_agent')
os.system('pip install cfonts')
os.system('pip install colorama')
os.system('pip install fake-useragent')
os.system('pip install pycountry')
os.system('pip install ms4')
os.system('pip install ToPython')
os.system('pip install psutil')
os.system('pip install pysocks')
os.system('pip install pycryptodome')
os.system('pip install curl2pyreqs')
os.system('pip install time') 
os.system('pip install python-cfonts') 
os.system('pip install Topython') 
os.system('pip install user_agent') 
os.system('pip install fake_useragent') 
os.system('pip install pyfiglet') 
os.system('pip install requests') 
os.system('pip install sys') 
print(' Please Wait …. Few Minutes Left')
os.system('pip install py_compile') 
os.system('pip install uuid') 
os.system('pip install os') 
os.system('pip install random') 
os.system('pip install datetime') 
os.system('pip install string') 
os.system('pip install webbrowser') 
os.system('pip install colorama') 
os.system('pip install bs4') 
os.system('pip install uuid') 
os.system('pip install secrets') 
os.system('pip install datetime') 
os.system('pip install InstagramAPI') 
os.system('pip install string') 
print(' Please Wait Installation Is Almost Complete')
os.system('pip install uuid4') 
os.system('pip install generate_user_agent') 
os.system('pip install datetime') 
os.system('pip install token_hex') 
os.system('pip install Fore') 
os.system('pip install uuid') 
os.system('pip install pysocks') 
os.system('pip install curl2pyreqs') 
os.system('cls' if os.name == 'nt' else 'clear') 
print("≠"*60)
print("The Installation Is Complete Now You Can Run Any Jacking File Without Any Error ")